<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="4" passed="4">
  <reporter-output>
    <line>
      <![CDATA[▀▄▀▄▀ DEVICE PROPERTIES: Capabilities [{reportPdfUrl=https://fifththird.reporting.perfectomobile.com/export/api/v1/test-executions/pdf?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324&_timestamp[0]=1533104681202, available=false, language=English, deviceName=CE0218220B2F94150C, deviceId=CE0218220B2F94150C, resolution=1440x2560, platform=ANY, wifiMacAddress=24:18:1d:95:b0:30, manufacturer=Samsung, mode=CONNECTED, password=, cradleId=BOS-D8-F4-3/VIRTUAL/03, deviceSessionId=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324, osVersion=7.0, driverClass=io.appium.java_client.android.AndroidDriver, platformVersion=Android, automationName=Appium, host=fifththird.perfectomobile.com, singleTestReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324&_timestamp[0]=1533104681202, inUse=true, takesScreenshot=true, javascriptEnabled=true, model=Galaxy S7 Edge, platformName=Android, firmware=hero2ltexx-user 7.0 NRD90M G935FXXU1DQJ8 release-keys, applicationName=Fifth Third, rotatable=true, testGridReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324&_timestamp[0]=1533104681202, os=Android, entityType=remote_web_driver, allocatedTo=dinesh.venkataraman@internal.53.com, serverConnector=, securityToken=, executionId=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324, webdriver.remote.sessionid=843d2d9e-20f8-4622-b0da-1175baa02af9, locationContextEnabled=true, scriptName=RemoteWebDriver, location=NA-US-BOS, linkType=lab, reportKey=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324, windTunnelReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324&_timestamp[0]=1533104681202, user=, operabilityRatingScore=100, cssSelectorsEnabled=true, status=Connected}] ▀▄▀▄▀]]>
    </line>
    <line>
      <![CDATA[█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]>
    </line>
    <line>
      <![CDATA[█ TEST STARTED: Validating invalid user name and password error message █]]>
    </line>
    <line>
      <![CDATA[█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: Given I start the application by the name "Fifth Third" ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[█ █ █  Context Switch Completed █ █ █ ]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: Given I start the application by the name "Fifth Third" ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: And I am using an AppiumDriver ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[█ █ █  Driver is an instance of AndroidDriver █ █ █ ]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: And I am using an AppiumDriver ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: When I enter "PerfectoMOBTest" and "Test@1234" ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[█ █ █  ------------------->NATIVE_APP █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  I am here in user name and password █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  *********************UserId got clicked █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  *********************UserId Got Entered █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  *********************Password got clicked █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  *********************Password Got Entered █ █ █ ]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: When I enter "PerfectoMOBTest" and "Test@1234" ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: And I click on login button ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: And I click on login button ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: Then I get an error message "User ID and Password invalid." ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[█ █ █  Error Text is ----------->User ID and Password invalid. █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  Assertion completed █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  Clicked Ok on Attention █ █ █ ]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: Then I get an error message "User ID and Password invalid." ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[<div style="display:block;margin-left:10px;"><div  class="teststeppass"><span class="teststeppass-label">T </span>Given I start the application by the name "Fifth Third"</div><div  class="teststeppass"><span class="teststeppass-label">T </span>And I am using an AppiumDriver</div><div  class="teststeppass"><span class="teststeppass-label">T </span>When I enter "PerfectoMOBTest" and "Test@1234"</div><div  class="teststeppass"><span class="teststeppass-label">T </span>And I click on login button</div><div  class="teststeppass"><span class="teststeppass-label">T </span>Then I get an error message "User ID and Password invalid."</div></div>]]>
    </line>
    <line>
      <![CDATA[▀▄▀▄▀ REPORTIUM URL: https://fifththird.reporting.perfectomobile.com/library?externalId%5B0%5D=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324&_timestamp%5B0%5D=1533104681202 ▀▄▀▄▀]]>
    </line>
    <line>
      <![CDATA[█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]>
    </line>
    <line>
      <![CDATA[█ TEST PASSED: Validating invalid user name and password error message █]]>
    </line>
    <line>
      <![CDATA[█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█]]>
    </line>
    <line>
      <![CDATA[█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]>
    </line>
    <line>
      <![CDATA[█ TEST STARTED: Validate no internet connection error message █]]>
    </line>
    <line>
      <![CDATA[█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: Given User is in login page ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[█ █ █  User is in login page █ █ █ ]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: Given User is in login page ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: And there is no internet connection ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: And there is no internet connection ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: When I have enter password as "Test@1234" ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[▀▄▀▄▀ DEVICE PROPERTIES: Capabilities [{reportPdfUrl=https://fifththird.reporting.perfectomobile.com/export/api/v1/test-executions/pdf?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327&_timestamp[0]=1533104692458, simpleIsVisibleCheck=true, available=false, language=English, deviceName=6CEDD7EA68F5F5211728B0554694B223BB4F86ED, deviceId=6CEDD7EA68F5F5211728B0554694B223BB4F86ED, resolution=1242x2208, mode=CONNECTED, password=, cradleId=BOS-E2-F1-5/VIRTUAL/05, deviceSessionId=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327, driverClass=io.appium.java_client.ios.IOSDriver, automationName=Appium, host=fifththird.perfectomobile.com, javascriptEnabled=true, model=iPhone-8 Plus, rotatable=true, entityType=remote_web_driver, serverHost=1.5.43.22:11605, executionId=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327, webdriver.remote.sessionid=dd927563-06a6-4996-af9d-1d85639cb42a, scriptName=RemoteWebDriver, operabilityRatingScore=100, cssSelectorsEnabled=true, status=Connected, bundleid=com.clairmail.fth.client, platform=ANY, wifiMacAddress=68:ef:43:e0:b5:f8, manufacturer=Apple, osVersion=11.4, platformVersion=11.4, singleTestReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327&_timestamp[0]=1533104692458, inUse=true, takesScreenshot=true, platformName=iOS, firmware=11.4, applicationName=Fifth Third, testGridReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327&_timestamp[0]=1533104692458, os=iOS, xcuitestFindOptimizations=true, allocatedTo=dinesh.venkataraman@internal.53.com, bundleId=com.apple.mobilesafari, serverConnector=, securityToken=, locationContextEnabled=true, location=NA-US-BOS, linkType=lab, reportKey=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327, windTunnelReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327&_timestamp[0]=1533104692458, user=}] ▀▄▀▄▀]]>
    </line>
    <line>
      <![CDATA[█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]>
    </line>
    <line>
      <![CDATA[█ TEST STARTED: Validating invalid user name and password error message █]]>
    </line>
    <line>
      <![CDATA[█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: Given I start the application by the name "Fifth Third" ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[█ █ █  Password got clicked █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  Password Got Entered █ █ █ ]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: When I have enter password as "Test@1234" ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: And I click on login button ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: And I click on login button ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: Then I get an no internet error message ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[█ █ █  Context Switch Completed █ █ █ ]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: Given I start the application by the name "Fifth Third" ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: And I am using an AppiumDriver ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[█ █ █  Driver is an instance of IOSDriver █ █ █ ]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: And I am using an AppiumDriver ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: When I enter "PerfectoMOBTest" and "Test@1234" ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[█ █ █  ------------------->NATIVE_APP █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  I am here in user name and password █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  Error Text is A connection error has occurred. You may experience delays. █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  *********************UserId got clicked █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  *********************UserId Got Entered █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  Clicked Ok on Attention █ █ █ ]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: Then I get an no internet error message ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[<div style="display:block;margin-left:10px;"><div  class="teststeppass"><span class="teststeppass-label">T </span>Given User is in login page</div><div  class="teststeppass"><span class="teststeppass-label">T </span>And there is no internet connection</div><div  class="teststeppass"><span class="teststeppass-label">T </span>When I have enter password as "Test@1234"</div><div  class="teststeppass"><span class="teststeppass-label">T </span>And I click on login button</div><div  class="teststeppass"><span class="teststeppass-label">T </span>Then I get an no internet error message</div><div style="display:block;margin-left:10px;"><div  class="pass"><span class="pass-label">P </span>Expected Internet not available text should be A connection error has occurred. You may experience delays. : Actual Internet not available text is A connection error has occurred. You may experience delays.</div></div></div>]]>
    </line>
    <line>
      <![CDATA[▀▄▀▄▀ REPORTIUM URL: https://fifththird.reporting.perfectomobile.com/library?externalId%5B0%5D=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324&_timestamp%5B0%5D=1533104681202 ▀▄▀▄▀]]>
    </line>
    <line>
      <![CDATA[█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]>
    </line>
    <line>
      <![CDATA[█ TEST PASSED: Validate no internet connection error message █]]>
    </line>
    <line>
      <![CDATA[█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█]]>
    </line>
    <line>
      <![CDATA[█ █ █  *********************Password got clicked █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  *********************Password Got Entered █ █ █ ]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: When I enter "PerfectoMOBTest" and "Test@1234" ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: And I click on login button ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: And I click on login button ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: Then I get an error message "User ID and Password invalid." ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[█ █ █  Error Text is ----------->User ID and Password invalid. █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  Assertion completed █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  Clicked Ok on Attention █ █ █ ]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: Then I get an error message "User ID and Password invalid." ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[<div style="display:block;margin-left:10px;"><div  class="teststeppass"><span class="teststeppass-label">T </span>Given I start the application by the name "Fifth Third"</div><div  class="teststeppass"><span class="teststeppass-label">T </span>And I am using an AppiumDriver</div><div  class="teststeppass"><span class="teststeppass-label">T </span>When I enter "PerfectoMOBTest" and "Test@1234"</div><div  class="teststeppass"><span class="teststeppass-label">T </span>And I click on login button</div><div  class="teststeppass"><span class="teststeppass-label">T </span>Then I get an error message "User ID and Password invalid."</div></div>]]>
    </line>
    <line>
      <![CDATA[▀▄▀▄▀ REPORTIUM URL: https://fifththird.reporting.perfectomobile.com/library?externalId%5B0%5D=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327&_timestamp%5B0%5D=1533104692458 ▀▄▀▄▀]]>
    </line>
    <line>
      <![CDATA[█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]>
    </line>
    <line>
      <![CDATA[█ TEST PASSED: Validating invalid user name and password error message █]]>
    </line>
    <line>
      <![CDATA[█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█]]>
    </line>
    <line>
      <![CDATA[█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]>
    </line>
    <line>
      <![CDATA[█ TEST STARTED: Validate no internet connection error message █]]>
    </line>
    <line>
      <![CDATA[█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: Given User is in login page ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[█ █ █  User is in login page █ █ █ ]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: Given User is in login page ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: And there is no internet connection ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[█ █ █  Wifi is swithed off █ █ █ ]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: And there is no internet connection ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: When I have enter password as "Test@1234" ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[█ █ █  Password got clicked █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  Password Got Entered █ █ █ ]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: When I have enter password as "Test@1234" ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: And I click on login button ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: And I click on login button ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[▄ ▄ ▄ BEGIN STEP: Then I get an no internet error message ▄ ▄ ▄]]>
    </line>
    <line>
      <![CDATA[█ █ █  Error Text is You're not connected to the internet. A network connection is required. █ █ █ ]]>
    </line>
    <line>
      <![CDATA[█ █ █  Clicked Ok on Attention █ █ █ ]]>
    </line>
    <line>
      <![CDATA[▀ ▀ ▀ END STEP: Then I get an no internet error message ▀ ▀ ▀]]>
    </line>
    <line>
      <![CDATA[<div style="display:block;margin-left:10px;"><div  class="teststeppass"><span class="teststeppass-label">T </span>Given User is in login page</div><div  class="teststeppass"><span class="teststeppass-label">T </span>And there is no internet connection</div><div  class="teststeppass"><span class="teststeppass-label">T </span>When I have enter password as "Test@1234"</div><div  class="teststeppass"><span class="teststeppass-label">T </span>And I click on login button</div><div  class="teststeppass"><span class="teststeppass-label">T </span>Then I get an no internet error message</div><div style="display:block;margin-left:10px;"><div  class="pass"><span class="pass-label">P </span>Expected Internet not available text should be You're not connected to the internet. A network connection is required. : Actual Internet not available text is You're not connected to the internet. A network connection is required.</div></div></div>]]>
    </line>
    <line>
      <![CDATA[▀▄▀▄▀ REPORTIUM URL: https://fifththird.reporting.perfectomobile.com/library?externalId%5B0%5D=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327&_timestamp%5B0%5D=1533104692458 ▀▄▀▄▀]]>
    </line>
    <line>
      <![CDATA[█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]>
    </line>
    <line>
      <![CDATA[█ TEST PASSED: Validate no internet connection error message █]]>
    </line>
    <line>
      <![CDATA[█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█]]>
    </line>
  </reporter-output>
  <suite name="Appium Demo Suite" duration-ms="166549" started-at="2018-08-01T06:24:40Z" finished-at="2018-08-01T06:27:26Z">
    <groups>
      <group name="@smoke">
        <method signature="src.main.resources.scenarios.fifththirdLogin.feature.Validate no internet connection error message()[pri:1001, instance:com.qmetry.qaf.automation.step.client.Scenario@3e9]" name="Validate no internet connection error message" class="com.qmetry.qaf.automation.step.client.Scenario"/>
        <method signature="src.main.resources.scenarios.fifththirdLogin.feature.Validating invalid user name and password error message()[pri:1000, instance:com.qmetry.qaf.automation.step.client.Scenario@3e8]" name="Validating invalid user name and password error message" class="com.qmetry.qaf.automation.step.client.Scenario"/>
        <method signature="src.main.resources.scenarios.fifththirdLogin.feature.Validate no internet connection error message()[pri:1003, instance:com.qmetry.qaf.automation.step.client.Scenario@3eb]" name="Validate no internet connection error message" class="com.qmetry.qaf.automation.step.client.Scenario"/>
        <method signature="src.main.resources.scenarios.fifththirdLogin.feature.Validating invalid user name and password error message()[pri:1002, instance:com.qmetry.qaf.automation.step.client.Scenario@3ea]" name="Validating invalid user name and password error message" class="com.qmetry.qaf.automation.step.client.Scenario"/>
      </group> <!-- @smoke -->
    </groups>
    <test name="Android 53 Test" duration-ms="73941" started-at="2018-08-01T06:24:40Z" finished-at="2018-08-01T06:25:54Z">
      <class name="com.qmetry.qaf.automation.step.client.Scenario">
        <test-method status="PASS" signature="setupSuit(org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3eb]" test-instance-name="Validating invalid user name and password error message" name="setupSuit" is-config="true" duration-ms="16" started-at="2018-08-01T11:54:40Z" finished-at="2018-08-01T11:54:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1e66f1f5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupSuit -->
        <test-method status="PASS" signature="setupTest(org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3eb]" test-instance-name="Validating invalid user name and password error message" name="setupTest" is-config="true" duration-ms="8" started-at="2018-08-01T11:54:40Z" finished-at="2018-08-01T11:54:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1e66f1f5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method status="PASS" signature="setup(org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3eb]" test-instance-name="Validating invalid user name and password error message" name="setup" is-config="true" duration-ms="1" started-at="2018-08-01T11:54:40Z" finished-at="2018-08-01T11:54:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1e66f1f5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="setupMethod(java.lang.reflect.Method, org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3eb]" test-instance-name="Validating invalid user name and password error message" name="setupMethod" is-config="true" duration-ms="1" started-at="2018-08-01T11:54:40Z" finished-at="2018-08-01T11:54:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qmetry.qaf.automation.step.client.Scenario.scenario()]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@1e66f1f5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="PASS" signature="Validating invalid user name and password error message()[pri:1002, instance:com.qmetry.qaf.automation.step.client.Scenario@3ea]" test-instance-name="Validating invalid user name and password error message" name="Validating invalid user name and password error message" duration-ms="37237" started-at="2018-08-01T11:54:40Z" finished-at="2018-08-01T11:55:17Z">
          <reporter-output>
            <line>
              <![CDATA[▀▄▀▄▀ DEVICE PROPERTIES: Capabilities [{reportPdfUrl=https://fifththird.reporting.perfectomobile.com/export/api/v1/test-executions/pdf?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324&_timestamp[0]=1533104681202, available=false, language=English, deviceName=CE0218220B2F94150C, deviceId=CE0218220B2F94150C, resolution=1440x2560, platform=ANY, wifiMacAddress=24:18:1d:95:b0:30, manufacturer=Samsung, mode=CONNECTED, password=, cradleId=BOS-D8-F4-3/VIRTUAL/03, deviceSessionId=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324, osVersion=7.0, driverClass=io.appium.java_client.android.AndroidDriver, platformVersion=Android, automationName=Appium, host=fifththird.perfectomobile.com, singleTestReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324&_timestamp[0]=1533104681202, inUse=true, takesScreenshot=true, javascriptEnabled=true, model=Galaxy S7 Edge, platformName=Android, firmware=hero2ltexx-user 7.0 NRD90M G935FXXU1DQJ8 release-keys, applicationName=Fifth Third, rotatable=true, testGridReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324&_timestamp[0]=1533104681202, os=Android, entityType=remote_web_driver, allocatedTo=dinesh.venkataraman@internal.53.com, serverConnector=, securityToken=, executionId=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324, webdriver.remote.sessionid=843d2d9e-20f8-4622-b0da-1175baa02af9, locationContextEnabled=true, scriptName=RemoteWebDriver, location=NA-US-BOS, linkType=lab, reportKey=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324, windTunnelReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324&_timestamp[0]=1533104681202, user=, operabilityRatingScore=100, cssSelectorsEnabled=true, status=Connected}] ▀▄▀▄▀]]>
            </line>
            <line>
              <![CDATA[█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]>
            </line>
            <line>
              <![CDATA[█ TEST STARTED: Validating invalid user name and password error message █]]>
            </line>
            <line>
              <![CDATA[█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: Given I start the application by the name "Fifth Third" ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[█ █ █  Context Switch Completed █ █ █ ]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: Given I start the application by the name "Fifth Third" ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: And I am using an AppiumDriver ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[█ █ █  Driver is an instance of AndroidDriver █ █ █ ]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: And I am using an AppiumDriver ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: When I enter "PerfectoMOBTest" and "Test@1234" ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[█ █ █  ------------------->NATIVE_APP █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  I am here in user name and password █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  *********************UserId got clicked █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  *********************UserId Got Entered █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  *********************Password got clicked █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  *********************Password Got Entered █ █ █ ]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: When I enter "PerfectoMOBTest" and "Test@1234" ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: And I click on login button ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: And I click on login button ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: Then I get an error message "User ID and Password invalid." ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[█ █ █  Error Text is ----------->User ID and Password invalid. █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  Assertion completed █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  Clicked Ok on Attention █ █ █ ]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: Then I get an error message "User ID and Password invalid." ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[<div style="display:block;margin-left:10px;"><div  class="teststeppass"><span class="teststeppass-label">T </span>Given I start the application by the name "Fifth Third"</div><div  class="teststeppass"><span class="teststeppass-label">T </span>And I am using an AppiumDriver</div><div  class="teststeppass"><span class="teststeppass-label">T </span>When I enter "PerfectoMOBTest" and "Test@1234"</div><div  class="teststeppass"><span class="teststeppass-label">T </span>And I click on login button</div><div  class="teststeppass"><span class="teststeppass-label">T </span>Then I get an error message "User ID and Password invalid."</div></div>]]>
            </line>
            <line>
              <![CDATA[▀▄▀▄▀ REPORTIUM URL: https://fifththird.reporting.perfectomobile.com/library?externalId%5B0%5D=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324&_timestamp%5B0%5D=1533104681202 ▀▄▀▄▀]]>
            </line>
            <line>
              <![CDATA[█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]>
            </line>
            <line>
              <![CDATA[█ TEST PASSED: Validating invalid user name and password error message █]]>
            </line>
            <line>
              <![CDATA[█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█]]>
            </line>
          </reporter-output>
        </test-method> <!-- Validating invalid user name and password error message -->
        <test-method status="PASS" signature="afterClass(org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3eb]" test-instance-name="Validating invalid user name and password error message" name="afterClass" is-config="true" duration-ms="1" started-at="2018-08-01T11:55:17Z" finished-at="2018-08-01T11:55:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1e66f1f5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestContext, org.testng.ITestResult)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3eb]" test-instance-name="Validating invalid user name and password error message" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-08-01T11:55:17Z" finished-at="2018-08-01T11:55:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1e66f1f5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=Validating invalid user name and password error message status=SUCCESS method=src.main.resources.scenarios.fifththirdLogin.feature.Validating invalid user name and password error message()[pri:1002, instance:com.qmetry.qaf.automation.step.client.Scenario@3ea] output=▀▄▀▄▀ DEVICE PROPERTIES: Capabilities [{reportPdfUrl=https://fifththird.reporting.perfectomobile.com/export/api/v1/test-executions/pdf?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324&_timestamp[0]=1533104681202, available=false, language=English, deviceName=CE0218220B2F94150C, deviceId=CE0218220B2F94150C, resolution=1440x2560, platform=ANY, wifiMacAddress=24:18:1d:95:b0:30, manufacturer=Samsung, mode=CONNECTED, password=, cradleId=BOS-D8-F4-3/VIRTUAL/03, deviceSessionId=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324, osVersion=7.0, driverClass=io.appium.java_client.android.AndroidDriver, platformVersion=Android, automationName=Appium, host=fifththird.perfectomobile.com, singleTestReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324&_timestamp[0]=1533104681202, inUse=true, takesScreenshot=true, javascriptEnabled=true, model=Galaxy S7 Edge, platformName=Android, firmware=hero2ltexx-user 7.0 NRD90M G935FXXU1DQJ8 release-keys, applicationName=Fifth Third, rotatable=true, testGridReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324&_timestamp[0]=1533104681202, os=Android, entityType=remote_web_driver, allocatedTo=dinesh.venkataraman@internal.53.com, serverConnector=, securityToken=, executionId=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324, webdriver.remote.sessionid=843d2d9e-20f8-4622-b0da-1175baa02af9, locationContextEnabled=true, scriptName=RemoteWebDriver, location=NA-US-BOS, linkType=lab, reportKey=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324, windTunnelReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324&_timestamp[0]=1533104681202, user=, operabilityRatingScore=100, cssSelectorsEnabled=true, status=Connected}] ▀▄▀▄▀]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="setup(org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3eb]" test-instance-name="Validate no internet connection error message" name="setup" is-config="true" duration-ms="1" started-at="2018-08-01T11:55:17Z" finished-at="2018-08-01T11:55:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1e66f1f5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="setupMethod(java.lang.reflect.Method, org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3eb]" test-instance-name="Validate no internet connection error message" name="setupMethod" is-config="true" duration-ms="0" started-at="2018-08-01T11:55:17Z" finished-at="2018-08-01T11:55:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qmetry.qaf.automation.step.client.Scenario.scenario()]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@1e66f1f5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="PASS" signature="Validate no internet connection error message()[pri:1003, instance:com.qmetry.qaf.automation.step.client.Scenario@3eb]" test-instance-name="Validate no internet connection error message" name="Validate no internet connection error message" duration-ms="14619" started-at="2018-08-01T11:55:17Z" finished-at="2018-08-01T11:55:32Z">
          <reporter-output>
            <line>
              <![CDATA[█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]>
            </line>
            <line>
              <![CDATA[█ TEST STARTED: Validate no internet connection error message █]]>
            </line>
            <line>
              <![CDATA[█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: Given User is in login page ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[█ █ █  User is in login page █ █ █ ]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: Given User is in login page ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: And there is no internet connection ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: And there is no internet connection ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: When I have enter password as "Test@1234" ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[█ █ █  Password got clicked █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  Password Got Entered █ █ █ ]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: When I have enter password as "Test@1234" ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: And I click on login button ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: And I click on login button ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: Then I get an no internet error message ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[█ █ █  Error Text is A connection error has occurred. You may experience delays. █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  Clicked Ok on Attention █ █ █ ]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: Then I get an no internet error message ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[<div style="display:block;margin-left:10px;"><div  class="teststeppass"><span class="teststeppass-label">T </span>Given User is in login page</div><div  class="teststeppass"><span class="teststeppass-label">T </span>And there is no internet connection</div><div  class="teststeppass"><span class="teststeppass-label">T </span>When I have enter password as "Test@1234"</div><div  class="teststeppass"><span class="teststeppass-label">T </span>And I click on login button</div><div  class="teststeppass"><span class="teststeppass-label">T </span>Then I get an no internet error message</div><div style="display:block;margin-left:10px;"><div  class="pass"><span class="pass-label">P </span>Expected Internet not available text should be A connection error has occurred. You may experience delays. : Actual Internet not available text is A connection error has occurred. You may experience delays.</div></div></div>]]>
            </line>
            <line>
              <![CDATA[▀▄▀▄▀ REPORTIUM URL: https://fifththird.reporting.perfectomobile.com/library?externalId%5B0%5D=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_41_1324&_timestamp%5B0%5D=1533104681202 ▀▄▀▄▀]]>
            </line>
            <line>
              <![CDATA[█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]>
            </line>
            <line>
              <![CDATA[█ TEST PASSED: Validate no internet connection error message █]]>
            </line>
            <line>
              <![CDATA[█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█]]>
            </line>
          </reporter-output>
        </test-method> <!-- Validate no internet connection error message -->
        <test-method status="PASS" signature="afterClass(org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3eb]" test-instance-name="Validate no internet connection error message" name="afterClass" is-config="true" duration-ms="1" started-at="2018-08-01T11:55:32Z" finished-at="2018-08-01T11:55:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1e66f1f5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestContext, org.testng.ITestResult)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3eb]" test-instance-name="Validate no internet connection error message" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-08-01T11:55:32Z" finished-at="2018-08-01T11:55:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1e66f1f5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=Validate no internet connection error message status=SUCCESS method=src.main.resources.scenarios.fifththirdLogin.feature.Validate no internet connection error message()[pri:1003, instance:com.qmetry.qaf.automation.step.client.Scenario@3eb] output=█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterTest(org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3eb]" test-instance-name="Validating invalid user name and password error message" name="afterTest" is-config="true" duration-ms="21558" started-at="2018-08-01T11:55:32Z" finished-at="2018-08-01T11:55:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1e66f1f5]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.qmetry.qaf.automation.step.client.Scenario -->
    </test> <!-- Android 53 Test -->
    <test name="IOS 53 Test" duration-ms="166549" started-at="2018-08-01T06:24:40Z" finished-at="2018-08-01T06:27:26Z">
      <class name="com.qmetry.qaf.automation.step.client.Scenario">
        <test-method status="PASS" signature="setupTest(org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3e9]" test-instance-name="Validating invalid user name and password error message" name="setupTest" is-config="true" duration-ms="11" started-at="2018-08-01T11:54:40Z" finished-at="2018-08-01T11:54:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@21d8bd6b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupTest -->
        <test-method status="PASS" signature="setup(org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3e9]" test-instance-name="Validating invalid user name and password error message" name="setup" is-config="true" duration-ms="1" started-at="2018-08-01T11:54:40Z" finished-at="2018-08-01T11:54:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@21d8bd6b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="setupMethod(java.lang.reflect.Method, org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3e9]" test-instance-name="Validating invalid user name and password error message" name="setupMethod" is-config="true" duration-ms="1" started-at="2018-08-01T11:54:40Z" finished-at="2018-08-01T11:54:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qmetry.qaf.automation.step.client.Scenario.scenario()]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@21d8bd6b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="PASS" signature="Validating invalid user name and password error message()[pri:1000, instance:com.qmetry.qaf.automation.step.client.Scenario@3e8]" test-instance-name="Validating invalid user name and password error message" name="Validating invalid user name and password error message" duration-ms="69718" started-at="2018-08-01T11:54:40Z" finished-at="2018-08-01T11:55:49Z">
          <reporter-output>
            <line>
              <![CDATA[▀▄▀▄▀ DEVICE PROPERTIES: Capabilities [{reportPdfUrl=https://fifththird.reporting.perfectomobile.com/export/api/v1/test-executions/pdf?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327&_timestamp[0]=1533104692458, simpleIsVisibleCheck=true, available=false, language=English, deviceName=6CEDD7EA68F5F5211728B0554694B223BB4F86ED, deviceId=6CEDD7EA68F5F5211728B0554694B223BB4F86ED, resolution=1242x2208, mode=CONNECTED, password=, cradleId=BOS-E2-F1-5/VIRTUAL/05, deviceSessionId=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327, driverClass=io.appium.java_client.ios.IOSDriver, automationName=Appium, host=fifththird.perfectomobile.com, javascriptEnabled=true, model=iPhone-8 Plus, rotatable=true, entityType=remote_web_driver, serverHost=1.5.43.22:11605, executionId=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327, webdriver.remote.sessionid=dd927563-06a6-4996-af9d-1d85639cb42a, scriptName=RemoteWebDriver, operabilityRatingScore=100, cssSelectorsEnabled=true, status=Connected, bundleid=com.clairmail.fth.client, platform=ANY, wifiMacAddress=68:ef:43:e0:b5:f8, manufacturer=Apple, osVersion=11.4, platformVersion=11.4, singleTestReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327&_timestamp[0]=1533104692458, inUse=true, takesScreenshot=true, platformName=iOS, firmware=11.4, applicationName=Fifth Third, testGridReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327&_timestamp[0]=1533104692458, os=iOS, xcuitestFindOptimizations=true, allocatedTo=dinesh.venkataraman@internal.53.com, bundleId=com.apple.mobilesafari, serverConnector=, securityToken=, locationContextEnabled=true, location=NA-US-BOS, linkType=lab, reportKey=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327, windTunnelReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327&_timestamp[0]=1533104692458, user=}] ▀▄▀▄▀]]>
            </line>
            <line>
              <![CDATA[█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]>
            </line>
            <line>
              <![CDATA[█ TEST STARTED: Validating invalid user name and password error message █]]>
            </line>
            <line>
              <![CDATA[█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: Given I start the application by the name "Fifth Third" ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[█ █ █  Context Switch Completed █ █ █ ]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: Given I start the application by the name "Fifth Third" ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: And I am using an AppiumDriver ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[█ █ █  Driver is an instance of IOSDriver █ █ █ ]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: And I am using an AppiumDriver ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: When I enter "PerfectoMOBTest" and "Test@1234" ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[█ █ █  ------------------->NATIVE_APP █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  I am here in user name and password █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  *********************UserId got clicked █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  *********************UserId Got Entered █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  *********************Password got clicked █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  *********************Password Got Entered █ █ █ ]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: When I enter "PerfectoMOBTest" and "Test@1234" ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: And I click on login button ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: And I click on login button ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: Then I get an error message "User ID and Password invalid." ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[█ █ █  Error Text is ----------->User ID and Password invalid. █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  Assertion completed █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  Clicked Ok on Attention █ █ █ ]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: Then I get an error message "User ID and Password invalid." ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[<div style="display:block;margin-left:10px;"><div  class="teststeppass"><span class="teststeppass-label">T </span>Given I start the application by the name "Fifth Third"</div><div  class="teststeppass"><span class="teststeppass-label">T </span>And I am using an AppiumDriver</div><div  class="teststeppass"><span class="teststeppass-label">T </span>When I enter "PerfectoMOBTest" and "Test@1234"</div><div  class="teststeppass"><span class="teststeppass-label">T </span>And I click on login button</div><div  class="teststeppass"><span class="teststeppass-label">T </span>Then I get an error message "User ID and Password invalid."</div></div>]]>
            </line>
            <line>
              <![CDATA[▀▄▀▄▀ REPORTIUM URL: https://fifththird.reporting.perfectomobile.com/library?externalId%5B0%5D=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327&_timestamp%5B0%5D=1533104692458 ▀▄▀▄▀]]>
            </line>
            <line>
              <![CDATA[█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]>
            </line>
            <line>
              <![CDATA[█ TEST PASSED: Validating invalid user name and password error message █]]>
            </line>
            <line>
              <![CDATA[█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█]]>
            </line>
          </reporter-output>
        </test-method> <!-- Validating invalid user name and password error message -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestContext, org.testng.ITestResult)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3e9]" test-instance-name="Validating invalid user name and password error message" name="afterMethod" is-config="true" duration-ms="1" started-at="2018-08-01T11:55:50Z" finished-at="2018-08-01T11:55:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@21d8bd6b]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=Validating invalid user name and password error message status=SUCCESS method=src.main.resources.scenarios.fifththirdLogin.feature.Validating invalid user name and password error message()[pri:1000, instance:com.qmetry.qaf.automation.step.client.Scenario@3e8] output=▀▄▀▄▀ DEVICE PROPERTIES: Capabilities [{reportPdfUrl=https://fifththird.reporting.perfectomobile.com/export/api/v1/test-executions/pdf?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327&_timestamp[0]=1533104692458, simpleIsVisibleCheck=true, available=false, language=English, deviceName=6CEDD7EA68F5F5211728B0554694B223BB4F86ED, deviceId=6CEDD7EA68F5F5211728B0554694B223BB4F86ED, resolution=1242x2208, mode=CONNECTED, password=, cradleId=BOS-E2-F1-5/VIRTUAL/05, deviceSessionId=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327, driverClass=io.appium.java_client.ios.IOSDriver, automationName=Appium, host=fifththird.perfectomobile.com, javascriptEnabled=true, model=iPhone-8 Plus, rotatable=true, entityType=remote_web_driver, serverHost=1.5.43.22:11605, executionId=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327, webdriver.remote.sessionid=dd927563-06a6-4996-af9d-1d85639cb42a, scriptName=RemoteWebDriver, operabilityRatingScore=100, cssSelectorsEnabled=true, status=Connected, bundleid=com.clairmail.fth.client, platform=ANY, wifiMacAddress=68:ef:43:e0:b5:f8, manufacturer=Apple, osVersion=11.4, platformVersion=11.4, singleTestReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327&_timestamp[0]=1533104692458, inUse=true, takesScreenshot=true, platformName=iOS, firmware=11.4, applicationName=Fifth Third, testGridReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327&_timestamp[0]=1533104692458, os=iOS, xcuitestFindOptimizations=true, allocatedTo=dinesh.venkataraman@internal.53.com, bundleId=com.apple.mobilesafari, serverConnector=, securityToken=, locationContextEnabled=true, location=NA-US-BOS, linkType=lab, reportKey=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327, windTunnelReportUrl=https://fifththird.reporting.perfectomobile.com/library?externalId[0]=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327&_timestamp[0]=1533104692458, user=}] ▀▄▀▄▀]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="setupMethod(java.lang.reflect.Method, org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3e9]" test-instance-name="Validate no internet connection error message" name="setupMethod" is-config="true" duration-ms="1" started-at="2018-08-01T11:55:50Z" finished-at="2018-08-01T11:55:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.qmetry.qaf.automation.step.client.Scenario.scenario()]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[org.testng.TestRunner@21d8bd6b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="PASS" signature="afterClass(org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3e9]" test-instance-name="Validating invalid user name and password error message" name="afterClass" is-config="true" duration-ms="0" started-at="2018-08-01T11:55:50Z" finished-at="2018-08-01T11:55:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@21d8bd6b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="setup(org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3e9]" test-instance-name="Validate no internet connection error message" name="setup" is-config="true" duration-ms="0" started-at="2018-08-01T11:55:50Z" finished-at="2018-08-01T11:55:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@21d8bd6b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="Validate no internet connection error message()[pri:1001, instance:com.qmetry.qaf.automation.step.client.Scenario@3e9]" test-instance-name="Validate no internet connection error message" name="Validate no internet connection error message" duration-ms="61181" started-at="2018-08-01T11:55:50Z" finished-at="2018-08-01T11:56:51Z">
          <reporter-output>
            <line>
              <![CDATA[█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]>
            </line>
            <line>
              <![CDATA[█ TEST STARTED: Validate no internet connection error message █]]>
            </line>
            <line>
              <![CDATA[█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: Given User is in login page ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[█ █ █  User is in login page █ █ █ ]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: Given User is in login page ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: And there is no internet connection ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[█ █ █  Wifi is swithed off █ █ █ ]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: And there is no internet connection ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: When I have enter password as "Test@1234" ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[█ █ █  Password got clicked █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  Password Got Entered █ █ █ ]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: When I have enter password as "Test@1234" ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: And I click on login button ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: And I click on login button ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[▄ ▄ ▄ BEGIN STEP: Then I get an no internet error message ▄ ▄ ▄]]>
            </line>
            <line>
              <![CDATA[█ █ █  Error Text is You're not connected to the internet. A network connection is required. █ █ █ ]]>
            </line>
            <line>
              <![CDATA[█ █ █  Clicked Ok on Attention █ █ █ ]]>
            </line>
            <line>
              <![CDATA[▀ ▀ ▀ END STEP: Then I get an no internet error message ▀ ▀ ▀]]>
            </line>
            <line>
              <![CDATA[<div style="display:block;margin-left:10px;"><div  class="teststeppass"><span class="teststeppass-label">T </span>Given User is in login page</div><div  class="teststeppass"><span class="teststeppass-label">T </span>And there is no internet connection</div><div  class="teststeppass"><span class="teststeppass-label">T </span>When I have enter password as "Test@1234"</div><div  class="teststeppass"><span class="teststeppass-label">T </span>And I click on login button</div><div  class="teststeppass"><span class="teststeppass-label">T </span>Then I get an no internet error message</div><div style="display:block;margin-left:10px;"><div  class="pass"><span class="pass-label">P </span>Expected Internet not available text should be You're not connected to the internet. A network connection is required. : Actual Internet not available text is You're not connected to the internet. A network connection is required.</div></div></div>]]>
            </line>
            <line>
              <![CDATA[▀▄▀▄▀ REPORTIUM URL: https://fifththird.reporting.perfectomobile.com/library?externalId%5B0%5D=dinesh.venkataraman@internal.53.com_RemoteWebDriver_18-08-01_06_24_52_1327&_timestamp%5B0%5D=1533104692458 ▀▄▀▄▀]]>
            </line>
            <line>
              <![CDATA[█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]>
            </line>
            <line>
              <![CDATA[█ TEST PASSED: Validate no internet connection error message █]]>
            </line>
            <line>
              <![CDATA[█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█]]>
            </line>
          </reporter-output>
        </test-method> <!-- Validate no internet connection error message -->
        <test-method status="PASS" signature="afterClass(org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3e9]" test-instance-name="Validate no internet connection error message" name="afterClass" is-config="true" duration-ms="1" started-at="2018-08-01T11:56:51Z" finished-at="2018-08-01T11:56:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@21d8bd6b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestContext, org.testng.ITestResult)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3e9]" test-instance-name="Validate no internet connection error message" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-08-01T11:56:51Z" finished-at="2018-08-01T11:56:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@21d8bd6b]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=Validate no internet connection error message status=SUCCESS method=src.main.resources.scenarios.fifththirdLogin.feature.Validate no internet connection error message()[pri:1001, instance:com.qmetry.qaf.automation.step.client.Scenario@3e9] output=█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterTest(org.testng.ITestContext)[pri:0, instance:com.qmetry.qaf.automation.step.client.Scenario@3e9]" test-instance-name="Validating invalid user name and password error message" name="afterTest" is-config="true" duration-ms="35151" started-at="2018-08-01T11:56:51Z" finished-at="2018-08-01T11:57:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@21d8bd6b]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.qmetry.qaf.automation.step.client.Scenario -->
    </test> <!-- IOS 53 Test -->
  </suite> <!-- Appium Demo Suite -->
</testng-results>
